/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent(props) {
  return (
    <>
      <div className="relative shrink-0 box-border h-auto text-red-600 bg-zinc-950 text-3xl mt-5 mx-auto max-sm:text-center max-sm:text-xl max-sm:mx-auto">
        <h1>
          <strong>
            This is just a test to see if I can sync this in order to have
            builder tools available.
          </strong>
        </h1>
      </div>
      <img
        loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets%2F56623995ce4b4b5bbaaeb5a16af2eb11%2F6236375cae144984bc8414e7249854ee?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F56623995ce4b4b5bbaaeb5a16af2eb11%2F6236375cae144984bc8414e7249854ee?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F56623995ce4b4b5bbaaeb5a16af2eb11%2F6236375cae144984bc8414e7249854ee?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F56623995ce4b4b5bbaaeb5a16af2eb11%2F6236375cae144984bc8414e7249854ee?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F56623995ce4b4b5bbaaeb5a16af2eb11%2F6236375cae144984bc8414e7249854ee?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F56623995ce4b4b5bbaaeb5a16af2eb11%2F6236375cae144984bc8414e7249854ee?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F56623995ce4b4b5bbaaeb5a16af2eb11%2F6236375cae144984bc8414e7249854ee?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F56623995ce4b4b5bbaaeb5a16af2eb11%2F6236375cae144984bc8414e7249854ee"
        className="aspect-square object-cover object-center w-full shrink-0 box-border min-h-[400px] min-w-[20px] overflow-hidden max-w-[1080px] mt-2.5 mx-auto"
      />
      <Counter className="flex flex-col relative shrink-0 box-border mt-5" />
    </>
  );
}
